var _frases = [
  "Enfrente os problemas e leve a melhor!",
  "Dê mais atenção ao que você tem de bom na sua vida!",
  "Para chegar ao topo, o que importa é começar!",
  "De nada adianta ter sonhos, se você não se empenhar em correr atrás.",
  "Preste atenção nas oportunidades que estão à sua frente!",
  "Positividade para começar o dia é colocar a sua fé em prática",
  "Não deixe nada nem ninguém estragar o seu bom humor",
  "Ontem já passou, é hora de planejar o futuro",
  "Você pode não ter o melhor do mundo, mas tem muito pelo que agradecer!",
  "Não deixe sua felicidade nas mãos de ninguém!",
  "Ninguém, além de você, está no controle de sua felicidade. Portanto, ajuste as velas e corrija e rumo.",
  "Você é capaz de escrever a sua nova história todos os dias",
  "Sua satisfação depende muito da sua determinação",
  "Qual a sua motivação maior ao acordar hoje?",
  "Hoje acordei pra viver, levantar e seguir em frente. Porque a vida sempre pede um pouco mais da gente.",
  "Nunca é tarde para fazer o que você realmente quer fazer",
  "Mais palavras para quê?",
  "Nunca duvide que você é especial!",
  "A beleza começa quando você decide ser você mesma.",
  "Tenha um objetivo na vida e lute sempre para alcançá-lo!",
  "Se quer viver uma vida feliz, amarre-se a um objetivo, não às pessoas ou aos objetos.",
  "A sua melhor chance é o hoje",
  "Um passo de cada vez e a sua vida pode mudar completamente",
  "Se tiver que amar, ame hoje. Se tiver que sorrir, sorria hoje. Se tiver que chorar, chore hoje. Pois o importante é viver hoje. O ontem já foi e o amanhã talvez não venha.",
  "Comece fazendo o que é necessário, depois o que é possível, e de repente você estará fazendo o impossível.",
  "Aproveite o seu presente!",
  "Sorria! Deus acaba de te dar uma nova chance de fazer coisas extraordinárias acontecerem.",
  "Todos os dias você possui uma nova chance de pensar diferente",
  "Nossas cabeças são redondas para que o pensamento possa mudar de direção.",
  "Encare a vida com mais leveza",
  "A vida é muito importante para ser levada a sério.",
  "Confie na esperança todos os dias!",
  "Eu sei que não se pode viver só de esperança, mas sem esperança não vale a pena viver.",

];